version: "2"
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:123@postgres/zamurobot
  postgres:
    image: postgres:12.7-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123
